SET SQLPROMPT "oracle: _USER > "
SET NULL "__NULL__"
SET LINESIZE 100
SET SUFFIX SQL
SET TIMING ON
SET COLSEP ","
SET TRIMSPOOL ON
SET PAGES 100
DEFINE_EDITOR=vi
ALTER SESSION SET NLS_DATE_FORMAT='YYYYMMDD HH24:MI:SS';
